config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Avo::Engine, at: Avo.configuration.root_path
    Avo::Engine.routes.draw do
      # This route is not protected, secure it with authentication if needed.
      get "dashboard", to: "tools#dashboard", as: :dashboard
      post "login_as/:id", to: "tools#login_as", as: :login_as
    end
  end
  resources :accounts, only: [ :create ] do
    resources :account_users, only: %i[create index destroy], module: :accounts
    member do
      get :switch
    end
  end
  namespace :inbound_webhooks do
    resources :github, controller: :github, only: [ :create ]
    resources :gitlab, controller: :gitlab, only: [ :create ]
  end
  get "/privacy", to: "static#privacy"
  get "/terms", to: "static#terms"

  authenticated :user do
    root to: "projects#index", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end
  get "/integrations/github/repositories", to: "integrations/github/repositories#index"
  resources :add_ons do
    collection do
      get :search
      get :default_values
    end
    member do
      post :restart
    end
    resource :metrics, only: [ :show ], module: :add_ons
    resources :endpoints, only: %i[edit update], module: :add_ons
    resources :processes, only: %i[index show], module: :add_ons
  end

  resources :providers, only: %i[index new create destroy]
  resources :projects do
    member do
      post :restart
    end
    collection do
      get "/:project_id/deployments", to: "projects/deployments#index", as: :root
    end
    resources :project_forks, only: %i[index edit create], module: :projects
    resources :volumes, only: %i[index new create destroy], module: :projects
    resources :processes, only: %i[index show create destroy], module: :projects
    resources :services, only: %i[index new create destroy update], module: :projects do
      resources :jobs, only: %i[create], module: :services
      resources :domains, only: %i[create destroy], module: :services do
        collection do
          post :check_dns
        end
      end
    end
    resources :metrics, only: [ :index ], module: :projects
    resources :project_add_ons, only: %i[create destroy], module: :projects
    resources :environment_variables, only: %i[index create destroy], module: :projects
    resources :deployments, only: %i[index show], module: :projects do
      collection do
        post :deploy
      end
      member do
        post :redeploy
        patch :kill
      end
    end
  end
  resources :clusters do
    member do
      post :transfer_ownership
      get :download_kubeconfig
      get :download_yaml
      get :logs
    end
    resource :metrics, only: [ :show ], module: :clusters
    member do
      post :test_connection
      post :retry_install
    end
    collection do
      post :check_k3s_ip_address
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      mount Sidekiq::Web => "/sidekiq"
    end
  end

  resources :notifications, only: [ :index ]
  resources :announcements, only: [ :index ]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: "users/sessions" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "async_render" => "async_renderer#async_render"

  get "/calculator", to: "static#calculator"
  # Public marketing homepage
  if Rails.application.config.local_mode
    get "/github_token", to: "local/pages#github_token"
    put "/github_token", to: "local/pages#update_github_token"
    root to: "projects#index"
  else
    root to: "static#index"
  end
end

app/views/clusters/cluster_types/instructions/_k3s.html.erb
<div class="card-form hidden card-k3s space-y-4" data-controller="k3s-instructions">
  <p data-k3s-instructions-target="instructions">
    <div data-k3s-instructions-target="step" data-validation="ip-address">
      1. Enter the IP address of your server:
      <div class="form-group mt-4">
        <%= form.label :ip_address, "IP Address" %>
        <%= form.text_field :ip_address, class: "input input-bordered w-full max-w-sm", data: { "k3s-instructions-target": "ipAddress" } %>
        <div class="form-hint" data-k3s-instructions-target="ipAddressMessage">
        </div>
      </div>
    </div>

    <div data-k3s-instructions-target="step" class="hidden" data-validation="validate-ip-address">
      2. SSH into the server and run:
      <div>
        <code
          data-k3s-instructions-target="installCommand"
          class="inline cursor-pointer"
          data-controller="clipboard"
          data-clipboard-text="TO_REPLACE"
        >
          TO_REPLACE
        </code>
      </div>
      <div class="text-sm mt-2">
        (You may have to run
          <code class="cursor-pointer" data-controller="clipboard" data-clipboard-text="sudo ufw allow 6443 && sudo ufw reload">sudo ufw allow 6443 && sudo ufw reload</code>
          to allow outside connections to K3s.)
      </div>

    </div>

    <div data-k3s-instructions-target="step" class="hidden">
      3. Once the install is complete, run:
      <div>
        <pre class="inline cursor-pointer" data-controller="clipboard" data-clipboard-text="sudo cat /etc/rancher/k3s/k3s.yaml">sudo cat /etc/rancher/k3s/k3s.yaml</pre>
      </div>
    </div>

    <div data-k3s-instructions-target="step" class="hidden">
      4. Copy the output and paste it here:
      <div class="form-group">
        <%= form.text_area :kubeconfig_output, class: "textarea textarea-bordered w-full max-w-lg h-48" %>
      </div>
    </div>

    <div>
      <button type="button" class="btn btn-primary" data-k3s-instructions-target="next" data-action="k3s-instructions#updateStep">Next</button>
    </div>
  </p>
</div>

app/views/clusters/cluster_types/instructions/_k8s.html.erb
<div class="card-form hidden card-k8s space-y-4">
  <div data-controller="card-select">
    <label class="mb-2">Which managed Kubernetes provider are you using?</label>
    <div class="form-group">
      <div class="flex gap-4">
        <select class="hidden" data-card-select-target="input">
          <option value="digitalocean">Digital Ocean</option>
          <option value="linode">Linode</option>
          <option value="linode">Other</option>
        </select>
        <%= render "clusters/instructions/cards/digitalocean" %>
        <%= render "clusters/instructions/cards/linode" %>
        <%= render "clusters/instructions/cards/other" %>
      </div>
    </div>

    <div class="my-10 has-styled-links">
      <%= render "clusters/instructions/instructions/digitalocean" %>
      <%= render "clusters/instructions/instructions/linode" %>
      <%= render "clusters/instructions/instructions/other" %>
    </div>
  </div>

  <%= render(FormFieldComponent.new(
    label: "Kubeconfig File",
    description: "The kubeconfig file for your cluster. Only YAML files are accepted."
  )) do %>
    <%= form.file_field :kubeconfig_file, class: "file-input w-full", accept: ".yaml,.yml" %>
    <label class="label">
      <span class="label-text-alt">* Required</span>
    </label>
  <% end %>

  <div class="form-footer">
    <%= form.button "Submit", class: "btn btn-primary" %>

    <% if form.object.new_record? %>
      <%= link_to t("cancel"), clusters_path, class: "btn btn-secondary" %>
    <% else %>
      <%= link_to t("cancel"), cluster_path(@cluster), class: "btn btn-secondary" %>
    <% end %>
  </div>
</div>